[build]
  command = 'npm run build'
  publish = 'dist'

[[redirects]]
  from = '/assets/*'
  to = '/assets/:splat'
  status = 200
  force = false

[[redirects]]
  from = '/*.js'
  to = '/:splat.js'
  status = 200
  force = false

[[redirects]]
  from = '/*.css'
  to = '/:splat.css'
  status = 200
  force = false

[[redirects]]
  from = '/*.svg'
  to = '/:splat.svg'
  status = 200
  force = false

[[redirects]]
  from = '/*.json'
  to = '/:splat.json'
  status = 200
  force = false

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200
